---
- hosts: all
  vars:
    GCP: false
  tasks:
    - import_role:
        name: gcp
      when: GCP is true

- hosts: all
  become: yes
  tasks:
    - debug:
        var: ansible_play_hosts

    - import_role:
        name: base
      when: "'localhost' not in ansible_play_hosts"
