---
- hosts: all
  become: yes
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: install base apt packages
      ansible.builtin.apt:
        pkg:
          - git
          - build-essential
          - vim
          - strace
          - net-tools
          - iputils-ping 
          - iproute2 
          - python3 
          - python3-pip
          - nmon 
          - iotop 
          - ca-certificates 
          - curl 
          - gnupg-agent
          - apt-transport-https 
          - software-properties-common
          - openjdk-8-jre 
          - bridge-utils
        state: latest
        update_cache: true

    - name: install pip dependencies
      ansible.builtin.pip:
        name:
          - ansible 
          - docker 
          - docker-compose

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
        state: latest
        update_cache: true

    - name: install headers matching kernel
      apt:
        pkg:
        - linux-headers-{{ansible_kernel}}

    - name: update /opt permissions
      file:
        path: /opt
        mode: '0777' 

    - name: git checkout from gtp5
      ansible.builtin.git:
        repo: https://github.com/free5gc/gtp5g.git
        dest: /opt

    - name: Build and install gtp module
      ansible.builtin.shell: |
        make clean
        make
        make install
      args:
        chdir: /opt/free5gc

    - name: git checkout prometheus
      ansible.builtin.git:
        repo: https://github.com/vegasbrianc/prometheus
        dest: /opt

    - name: run prometheus docker compose stack
      community.docker.docker_compose:
        project_src: /opt/prometheus
