---
- hosts: all
  become: yes
  vars:
    # install gtp module
    - installGTP: true
    # set to true to deploy a local fluentd instance
    - deployFluentd: true
    # set to true to deploy a local nprobe instance and listen to eth0
    - deployNprobe: false
    # set to true to deploy a local kafka instance, if false then external kafka is expected
    - deployKafka: true
    # set to true to deploy a local kafdrop instance
    - deployKafdrop: false
    # set the IP/hostname of the external Kafka instance to connect to
    - externalKafkaAddress: "localhost"
    # kafka port internal/external
    - kafkaPort: 29092
    # set to true to deploy a full prometheus/grafana/cadvisor stack, else deploy just a cAdvisor and connect to kafka
    - deployPrometheus: false
    # set to true to deploy portainer
    - deployPortainer: false
  tasks:
    - import_role:
        name: base
