---
- hosts: all
  become: yes
  tasks:
    - name: install base apt packages
      ansible.builtin.apt:
        pkg:
        - git
        - build-essential
        - vim
        - strace
        - net-tools
        - iputils-ping 
        - iproute2 
        - python3 
        - python3-pip
        - nmon 
        - iotop 
        - ca-certificates 
        - curl 
        - gnupg-agent
        - apt-transport-https 
        - software-properties-common
        - openjdk-8-jre 
        - bridge-utils

    - name: install pip dependencies
      ansible.builtin.pip:
        name:
          - ansible 
          - docker 
          - docker-compose