- name: template docker compose file
  ansible.builtin.template:
    src: docker-compose.yaml
    dest: ./free5gc-compose.yaml
    mode: '0644'    

- name: start free5gc instance
  community.docker.docker_compose:
    project_src: .
    files:
    - free5gc-compose.yaml

- pause:
    seconds: 10