- name: set imsi vars
  set_fact: 
    imsi: "{{ item }}"
    plmnid: 20893

- set_fact: 
    payload: "{{ lookup('template', './templates/ue.json') }}"

- name: create subscriber
  uri: 
    url: 'http://{{ ansible_default_ipv4.address }}/api/subscriber/imsi-{{ imsi }}/{{ plmnid }}'
    method: POST
    return_content: yes
    body: '{{ payload }}'
    body_format: json
    status_code: 201
    follow_redirects: all
    headers:
      Token: admin
