---
version: '3'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    # networks: 
    #   - kafka_network
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"

  broker:
    image: wurstmeister/kafka
    container_name: broker
    # networks: 
    #   - kafka_network
    ports:
      - "{{kafkaPort}}:{{kafkaPort}}"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:{{kafkaPort}},INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL_SAME_HOST://{{ ansible_default_ipv4.address }}:{{kafkaPort}}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

# networks:
#   kafka_network:
#     name: kafka_docker_example_net